/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package payment.tracker

import kotlin.test.Test
import kotlin.test.assertNotNull

class PaymentTrackerTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = PaymentTracker()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
