/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package payment.tracker

class PaymentTracker {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(PaymentTracker().greeting)
}
